"""add chapter_num to chapter

Revision ID: 063cf102efaf
Revises: d5f486e4d318
Create Date: 2025-04-14 12:28:02.769999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '063cf102efaf'
down_revision: Union[str, None] = 'd5f486e4d318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('chapter_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'chapter_num')
    # ### end Alembic commands ###
