"""replace hardcoded created_at and updated_at for UserCourseFinishedChapters

Revision ID: 191174a51200
Revises: 7352d1b7385a
Create Date: 2025-05-21 16:41:59.278474

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import func  # Import func for NOW()

# revision identifiers, used by Alembic.
revision: str = "191174a51200"
down_revision: str | None = "7352d1b7385a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add created_at column as nullable
    op.add_column(
        "usercoursefinishedchapter",
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    # Add updated_at column as nullable initially
    op.add_column(
        "usercoursefinishedchapter",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    # Populate created_at and updated_at for existing rows
    # Define the table structure for the update statement
    usercoursefinishedchapter_table = sa.table(
        "usercoursefinishedchapter",
        sa.column("created_at", sa.DateTime()),
        sa.column("updated_at", sa.DateTime()),
        # Add other columns of the table if they were part of a composite key needed for an update,
        # but for setting timestamps, just the timestamp columns are fine.
    )

    # Use func.now() for database's current timestamp
    # For PostgreSQL, this translates to NOW()
    op.execute(
        usercoursefinishedchapter_table.update().values(
            created_at=func.now(), updated_at=func.now()
        )
    )

    # Now, alter updated_at to be non-nullable as per the model
    op.alter_column("usercoursefinishedchapter", "updated_at", nullable=False)

    # created_at remains nullable=True as per TimeStampMixin, so no alter_column needed for it.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usercoursefinishedchapter", "updated_at")
    op.drop_column("usercoursefinishedchapter", "created_at")
    # ### end Alembic commands ###
