"""add 'completed' to chapter

Revision ID: 5264a5b1707d
Revises: 92163a06c402
Create Date: 2025-06-17 15:11:09.841196

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5264a5b1707d"
down_revision: str | None = "92163a06c402"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # add as nullable
    op.add_column(
        "chapter",
        sa.Column("completed", sa.Boolean(), nullable=True),
    )
    # set existing rows to false
    op.execute("UPDATE chapter SET completed = false")
    # make it non-nullable
    op.alter_column("chapter", "completed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chapter", "completed")
    # ### end Alembic commands ###
