"""adjust chapter nullability

Revision ID: 5c2d4ff10905
Revises: 063cf102efaf
Create Date: 2025-05-15 12:34:00.697280

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c2d4ff10905"
down_revision: str | None = "063cf102efaf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chapter", "chapter_num", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "chapterpoint", "chapter_point_num", existing_type=sa.INTEGER(), nullable=False
    )
    # op.create_unique_constraint('unique_user_course', 'usercourse', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_course", "usercourse", type_="unique")
    op.alter_column(
        "chapterpoint", "chapter_point_num", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("chapter", "chapter_num", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
