"""add usercourse associationtable for finished chapters

Revision ID: 7352d1b7385a
Revises: f99e09d512c6
Create Date: 2025-05-19 09:26:42.464999

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7352d1b7385a"
down_revision: str | None = "f99e09d512c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usercoursefinishedchapter",
        sa.Column("user_course_user_id", sa.Uuid(), nullable=False),
        sa.Column("user_course_course_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.id"],
            name="fk_usercoursefinishedchapter_chapter_id_chapter",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_course_user_id", "user_course_course_id"],
            ["usercourse.user_id", "usercourse.course_id"],
            name="fk_usercoursefinishedchapter_usercourse",
        ),
        sa.PrimaryKeyConstraint(
            "user_course_user_id", "user_course_course_id", "chapter_id"
        ),
    )
    # op.create_unique_constraint('unique_user_course', 'usercourse', ['user_id', 'course_id'])
    op.drop_column("usercourse", "finished_chapters")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usercourse",
        sa.Column(
            "finished_chapters",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # op.drop_constraint("unique_user_course", "usercourse", type_="unique")
    op.drop_table("usercoursefinishedchapter")
    # ### end Alembic commands ###
