"""add test_code to chapter

Revision ID: 92163a06c402
Revises: abef593b406c
Create Date: 2025-06-11 14:29:03.736206

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92163a06c402"
down_revision: str | None = "abef593b406c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chapter", sa.Column("test_code", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chapter", "test_code")
    # ### end Alembic commands ###
