"""make course title unique

Revision ID: abef593b406c
Revises: 191174a51200
Create Date: 2025-06-05 10:00:07.637135

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abef593b406c"
down_revision: str | None = "191174a51200"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_course_title", "course", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_course_title", "course", type_="unique")
    # ### end Alembic commands ###
